cookie:
  expiry_days: 30
  key: moviot2024
  name: moviot
credentials:
  usernames:
    kadmin:
      email: xvuong@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: Vuong Le
      password: $2b$12$hxvts1loNyH4XKT98HIQ5eiHZin5mqyc5W77mPN1txNTmGi4eeM/W
      roles:
      - admin
    pparker:
      email: pparker@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: Peter Parker
      password: $2b$12$R56STmabgUeYII06uVKFk.Xq0uMOMr3TVXiqhAr3yEva6dvnPGVZy
      roles:
      - editor
      - viewer
    rmiller:
      email: rmiller@gmail.com
      name: Rebecca Miller
      password: $2b$12$0nz56cbnVEUd6/L6yMOgduHHsn73LdyzW2LdkHkYTUoWXJL9/IKSe
      roles:
      - maker
      - viewer
